version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: db_lesson
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: db_lesson
      DB_USER: db_user
      DB_PASSWORD: db_password
      DB_HOST: db
      DB_PORT: 3306

volumes:
  mysql_data:
