# Generated by Django 4.2.13 on 2024-05-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('elementos_list', models.JSONField()),
                ('tipo_elementos', models.CharField(max_length=100)),
                ('tipo_descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Textos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('lesson', 'Lesson'), ('observation', 'Observation'), ('incidente', 'Incident')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TextosLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.labels')),
                ('textos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.textos')),
            ],
        ),
        migrations.CreateModel(
            name='DadosLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dados')),
                ('labels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.labels')),
            ],
        ),
    ]
