# Generated by Django 4.2.13 on 2024-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_textos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textos',
            name='tipo',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('observation', 'Observation'), ('incidente', 'Incident')], max_length=100),
        ),
    ]
